#ifndef DEFINES_H_INCLUDED
#define DEFINES_H_INCLUDED

#define BFD_MEMORY_ROWS 24
#define BFD_SPACING 4
#define BFD_WIDTH 640
#define BFD_HEIGHT 480
#define BFD_TEXTAREA_WIDTH 540
#define BFD_CODE_HEIGHT 360
#define BFD_OUTPUT_HEIGHT 90
#define BFD_INPUT_DLG_WIDTH  320
#define BFD_INPUT_DLG_HEIGHT 200
#define BFD_TRACE_MAX 1000000
#define BFD_TRACE_ALTER 50000

typedef const char* error;

#endif // DEFINES_H_INCLUDED
